import { Inter } from "next/font/google";

export const metadata = {
  title: "Web tutorials",
  description: "Generated by taewoo",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <h1>
          <a href="/">WEB</a>
          <ol>
            <li>
              <a href="/read/1">html</a>
            </li>
            <li>
              <a href="/read/2">css</a>
            </li>
          </ol>
        </h1>
        {children}
        <ul>
          <li>
            <a href="/create">Create</a>
          </li>
          <li>
            <a href="/update/1">Update</a>
          </li>
          <li>
            <input type="button" value="delete" />
          </li>
        </ul>
      </body>
    </html>
  );
}
